version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - pwd
      - ls -la
      - docker info
      - docker images
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ls -la
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - LuaIntf/LuaIntf.h
  discard-paths: yes
